version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Declaro la persistencia de datos de PostgreSQL

  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    ports:
      - "8085:8085"  
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_HTTP_PORT: 8085  
    command: ['start-dev', '--http-port=8085']
    depends_on:
      - postgres

volumes:
  postgres_data:  # Declaración de volumen para persistencia
  #Queda en este mismo scope el realm.json para importar en el servidor