version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos de PostgreSQL

  keycloak:
    build:
      context: . # Construye la imagen usando el Dockerfile en el directorio actual
    ports:
      - "8085:8085"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_HTTP_PORT: 8085
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    command: [ 'start-dev', '--http-port=8085', '--import-realm' ]
    depends_on:
      - postgres

volumes:
  postgres_data: # Declaración de volumen para persistencia
